apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oi3izmqpl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oi3izmqpl-nodejs 
  name: oi3izmqpl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: oi3izmqpl-nodejs 
